apiVersion: apps/v1
kind: Deployment
metadata:
  name: accept1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accept1
  template:
    metadata:
      labels:
        app: accept1
    spec:
      containers:
      - image: okteto.dev/accept1:latest
        name: accept1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2150400b-80af-429d-abcc-f17e85e34242"
        - name: Vless_Path
          value: "/toesoesf235"
        - name: Vmess_UUID
          value: "c1d02c36-add0-4beb-b64c-01ab1c926f0f"
        - name: Vmess_Path
          value: "/woekdhfgw243"
        - name: Share_Path
          value: "/v2link"
