apiVersion: v1
kind: Service
metadata:
  name: accept1
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "accept1"
    port: 8080
  selector:
    app: accept1
